### ISSUE TITLE
Intratime-checker is not working on Windows Server 2019

### ISSUE THREAD

**Issue by chemamartinez** [alberpilot/intratime-checker#3]
Hi team,

I have tried to use it in a Windows Server 2019 but didn't work.

<img width="1059" alt="Captura de pantalla 2019-07-26 a las 16 21 31" src="https://user-images.githubusercontent.com/29475387/61958507-c75fbd00-afc1-11e9-812e-2147ccfe09c3.png">

It is a know bug? Is there any documentation on this?

Thanks in advance.

**Comment by alberpilot** [comment]
Hello @chemamartinez 

  Please enable debug mode and paste the logs. 

Regardos,
